version: '3.8'
services:
  model_server:
    build:
      context: .
      dockerfile: docker/Dockerfile.model_server
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    restart: unless-stopped
